openapi: '3.0.2'
info:
  title: Api Aula 14
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:             
  /users:
    get:
      operationId: getUsuarios
      summary: Obtém todos os usuários do sistema
      tags:
        - Get
      responses:
        '200':
          description: Lista de usuários
          content:
            appication/json:
              schema:
                type: object
                properties:
                  name:
                    type: array
                    example: bolodefuba
                  email:
                    type: array
                    example: foo@bar.com.br
                  password:
                    type: array
                    example: jaacaboujessica?
                  id:
                    type: array
                    example: 1
  /cadastrar:
    post:
      operationId: postUsuarios
      summary: Cadastra um usuários do sistema
      tags:
        - Posts
      requestBody:
        content:
          application/json:
            schema:
                type: object
                properties:
                  name:
                    type: array
                    example: bolodefuba
                  email:
                    type: array
                    example: foo@bar.com.br
                  password:
                    type: array
                    example: jaacaboujessica?
      responses:
        '200':
          description: Adicionar usuário
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: array
                    example: Usuário adicionado com sucesso.
        '400':
          description: Dados inválidos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: array
                    example: Dados inválidos.
components:
  schemas:
    Usuario:
      type: object
      properties:
        name:
          type: string
          description: Nome do usuário
          example: bolodefuba
        email:
          type: string
          description: E-mail do usuário
          example: foo@bar.com.br
        password:
          type: string
          description: Senha do usuário
          example: jaacaboujessica?
        id:
          type: integer
          description: Id do usuário
          example: 9
